Implement compileTables missing method
yajra/laravel-oci8 pull request #868
Opened 2024-07-15 12:43 UTC by ErDiabIo

Hi, 

This pr is for implemente the missing method compileTables from laravel

```php
compileTables
```

i write the following query for get all table from database

```sql
SELECT all_tab_comments.table_name AS "name"
FROM all_tab_comments
         JOIN all_tables ON all_tab_comments.table_name = all_tables.table_name
WHERE all_tab_comments.owner = '{owner}'
  AND all_tab_comments.table_type IN ('TABLE')
ORDER BY all_tab_comments.table_name;
```

2024-07-20 08:06 UTC, yajra commented
Thank you for the PR, the initial review looks good with a test. 

I will review this further as soon as I can.

2024-07-20 08:20 UTC, yajra requested changes
Running on local, `Schema::getTables()` returns duplicates and other fields are null.

```php
    [
      "name" => "JOBS",
      "schema" => null,
      "size" => null,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
    [
      "name" => "JOBS",
      "schema" => null,
      "size" => null,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
    [
      "name" => "JOB_BATCHES",
      "schema" => null,
      "size" => null,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
    [
      "name" => "JOB_BATCHES",
      "schema" => null,
      "size" => null,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
    [
      "name" => "JOB_BATCHES",
      "schema" => null,
      "size" => null,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
    [
      "name" => "JOB_BATCHES",
      "schema" => null,
      "size" => null,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
```

Using SQLite:

```php
    [
      "name" => "cache",
      "schema" => null,
      "size" => 8192,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
    [
      "name" => "cache_locks",
      "schema" => null,
      "size" => 8192,
      "comment" => null,
      "collation" => null,
      "engine" => null,
    ],
```

2024-07-20 08:35 UTC, yajra commented
Maybe MySQL would return more values, I suggest we try to match it. Thanks!

2024-07-22 10:03 UTC, ErDiabIo reviewed
Hi, 
I've updated the query to remove duplicates and add the missing information.

the new query 

```sql
SELECT ALL_TAB_COMMENTS.TABLE_NAME                                              AS "NAME",
       ALL_TABLES.OWNER                                                         AS "SCHEMA",
       COALESCE(ROUND(SUM(USER_SEGMENTS.BYTES) / 1024 / 1024, 2), 0)            AS "SIZE",
       ALL_TAB_COMMENTS.COMMENTS                                                AS "COMMENTS",
       (SELECT VALUE FROM NLS_DATABASE_PARAMETERS WHERE PARAMETER = 'NLS_SORT') AS "COLLATION"
FROM ALL_TABLES
         JOIN ALL_TAB_COMMENTS ON ALL_TAB_COMMENTS.TABLE_NAME = ALL_TABLES.TABLE_NAME
         LEFT JOIN USER_SEGMENTS ON USER_SEGMENTS.SEGMENT_NAME = ALL_TABLES.TABLE_NAME
WHERE ALL_TABLES.OWNER = '{OWNER}'
  AND ALL_TAB_COMMENTS.OWNER = '{OWNER}'
  AND ALL_TAB_COMMENTS.TABLE_TYPE IN ('TABLE')
GROUP BY ALL_TAB_COMMENTS.TABLE_NAME, ALL_TABLES.OWNER, ALL_TABLES.NUM_ROWS, ALL_TABLES.AVG_ROW_LEN, ALL_TABLES.BLOCKS,
         ALL_TAB_COMMENTS.COMMENTS
order by all_tab_comments.table_name;
```

2024-07-30 05:02 UTC, yajra requested changes

2024-07-30 05:02 UTC, yajra commented on src/Oci8/Schema/Grammars/OracleGrammar.php
> +    public function compileTables(string $owner): string
```suggestion
    public function compileTables(string $owner): string
    {
        return 'select lower(all_tab_comments.table_name)  as "name",
                lower(all_tables.owner) as "schema",
                sum(user_segments.bytes) as "size",
                all_tab_comments.comments as "comments",
                (select lower(value) from nls_database_parameters where parameter = \'NLS_SORT\') as "collation"
            from all_tables
                join all_tab_comments on all_tab_comments.table_name = all_tables.table_name
                left join user_segments on user_segments.segment_name = all_tables.table_name
            where all_tables.owner = \''.strtoupper($owner).'\'
                and all_tab_comments.owner = \''.strtoupper($owner).'\'
                and all_tab_comments.table_type in (\'TABLE\')
            group by all_tab_comments.table_name, all_tables.owner, all_tables.num_rows,
                all_tables.avg_row_len, all_tables.blocks, all_tab_comments.comments
            order by all_tab_comments.table_name';
    }
```

- Fix `NLS_SORT`
- Use `lower` on name, schema, and collation to match other drivers response
- Use `bytes` in size

2024-07-31 03:03 UTC, yajra approved these changes

2024-07-31 05:30 UTC, merged

2024-07-31 05:43 UTC, yajra commented
Release on https://github.com/yajra/laravel-oci8/releases/tag/v11.5.0 🚀 Thanks!